// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMDbryGsKzMWjsNxGv8Nq6B8jVJ4Q32BU',
    appId: '1:980254371483:web:4990eac367ebfe9002e03e',
    messagingSenderId: '980254371483',
    projectId: 'chat-app-e7c0a',
    authDomain: 'chat-app-e7c0a.firebaseapp.com',
    storageBucket: 'chat-app-e7c0a.firebasestorage.app',
    measurementId: 'G-EEZQD8N9M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnxtCRaadcQjfOwcg6Ob14ENKjR15wyb4',
    appId: '1:980254371483:android:773523beded6cf2002e03e',
    messagingSenderId: '980254371483',
    projectId: 'chat-app-e7c0a',
    storageBucket: 'chat-app-e7c0a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYb1OO0NKC673guUHDS1UAghr7n94HyKQ',
    appId: '1:980254371483:ios:46e2217b4bbe9d2002e03e',
    messagingSenderId: '980254371483',
    projectId: 'chat-app-e7c0a',
    storageBucket: 'chat-app-e7c0a.firebasestorage.app',
    iosBundleId: 'com.example.day9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYb1OO0NKC673guUHDS1UAghr7n94HyKQ',
    appId: '1:980254371483:ios:46e2217b4bbe9d2002e03e',
    messagingSenderId: '980254371483',
    projectId: 'chat-app-e7c0a',
    storageBucket: 'chat-app-e7c0a.firebasestorage.app',
    iosBundleId: 'com.example.day9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMDbryGsKzMWjsNxGv8Nq6B8jVJ4Q32BU',
    appId: '1:980254371483:web:9a7f5c756d71053802e03e',
    messagingSenderId: '980254371483',
    projectId: 'chat-app-e7c0a',
    authDomain: 'chat-app-e7c0a.firebaseapp.com',
    storageBucket: 'chat-app-e7c0a.firebasestorage.app',
    measurementId: 'G-XZEX296XKT',
  );
}
